/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.117
 * Generated at: 2026-05-09 12:49:39 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.*;
import com.bank.model.BankAccount;
import com.bank.model.Transaction;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(6);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("java.util");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.LinkedHashSet<>(3);
    _jspx_imports_classes.add("com.bank.model.BankAccount");
    _jspx_imports_classes.add("com.bank.model.Transaction");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");

    String message = (String) request.getAttribute("message");
    List<BankAccount> accounts = (List<BankAccount>) request.getAttribute("accounts");
    if (accounts == null) {
        accounts = (List<BankAccount>) session.getAttribute("accounts");
    }

      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("    <meta charset=\"UTF-8\">\n");
      out.write("    <title>Bank Account System</title>\n");
      out.write("    <style>\n");
      out.write("        body { font-family: Arial, sans-serif; margin: 24px; }\n");
      out.write("        fieldset { margin-bottom: 20px; padding: 16px; }\n");
      out.write("        label { display: inline-block; width: 150px; margin-bottom: 8px; }\n");
      out.write("        input, select { width: 220px; }\n");
      out.write("        table { border-collapse: collapse; width: 100%; margin-top: 12px; }\n");
      out.write("        th, td { border: 1px solid #ccc; padding: 8px; text-align: left; }\n");
      out.write("        th { background: #f4f4f4; }\n");
      out.write("        .message { padding: 10px; border: 1px solid #999; background: #f9f9f9; margin-bottom: 18px; }\n");
      out.write("    </style>\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("    <h1>Bank Account Web App</h1>\n");
      out.write("    <p>Use the form below to create accounts and process deposits, withdrawals, or transfers.</p>\n");
      out.write("\n");
      out.write("    ");
 if (message != null && !message.isEmpty()) { 
      out.write("\n");
      out.write("        <div class=\"message\">");
      out.print( message );
      out.write("</div>\n");
      out.write("    ");
 } 
      out.write("\n");
      out.write("\n");
      out.write("    <form method=\"post\" action=\"bank\">\n");
      out.write("        <fieldset>\n");
      out.write("            <legend>Account Setup</legend>\n");
      out.write("            <label for=\"name\">Account Holder Name</label>\n");
      out.write("            <input type=\"text\" id=\"name\" name=\"name\" required /> <br />\n");
      out.write("            <label for=\"number\">Account Number</label>\n");
      out.write("            <input type=\"number\" id=\"number\" name=\"number\" required /> <br />\n");
      out.write("            <label for=\"initialDeposit\">Initial Deposit</label>\n");
      out.write("            <input type=\"number\" id=\"initialDeposit\" name=\"initialDeposit\" step=\"0.01\" value=\"0\" />\n");
      out.write("        </fieldset>\n");
      out.write("\n");
      out.write("        <fieldset>\n");
      out.write("            <legend>Transaction</legend>\n");
      out.write("            <label for=\"action\">Action</label>\n");
      out.write("            <select id=\"action\" name=\"action\">\n");
      out.write("                <option value=\"create\">Create / Update Account</option>\n");
      out.write("                <option value=\"deposit\">Deposit</option>\n");
      out.write("                <option value=\"withdraw\">Withdraw</option>\n");
      out.write("                <option value=\"transfer\">Transfer</option>\n");
      out.write("            </select><br />\n");
      out.write("            <label for=\"amount\">Amount</label>\n");
      out.write("            <input type=\"number\" id=\"amount\" name=\"amount\" step=\"0.01\" value=\"0\" /> <br />\n");
      out.write("            <label for=\"receiver\">Receiver Account # (transfer only)</label>\n");
      out.write("            <input type=\"number\" id=\"receiver\" name=\"receiver\" />\n");
      out.write("        </fieldset>\n");
      out.write("\n");
      out.write("        <button type=\"submit\">Submit</button>\n");
      out.write("    </form>\n");
      out.write("\n");
      out.write("    ");
 if (accounts != null && !accounts.isEmpty()) { 
      out.write("\n");
      out.write("        <h2>Account Statements</h2>\n");
      out.write("        ");
 for (com.bank.model.BankAccount account : accounts) { 
      out.write("\n");
      out.write("            <h3>");
      out.print( account.getName() );
      out.write(" (Account #: ");
      out.print( account.getAccountNumber() );
      out.write(")</h3>\n");
      out.write("            <p>Balance: <strong>");
      out.print( String.format("%.2f", account.getBalance()) );
      out.write("</strong></p>\n");
      out.write("            <table>\n");
      out.write("                <thead>\n");
      out.write("                    <tr>\n");
      out.write("                        <th>Date</th>\n");
      out.write("                        <th>Description</th>\n");
      out.write("                        <th>Amount</th>\n");
      out.write("                        <th>Balance</th>\n");
      out.write("                    </tr>\n");
      out.write("                </thead>\n");
      out.write("                <tbody>\n");
      out.write("                ");
 for (com.bank.model.Transaction tx : account.getTransactions()) { 
      out.write("\n");
      out.write("                    <tr>\n");
      out.write("                        <td>");
      out.print( tx.getDate() );
      out.write("</td>\n");
      out.write("                        <td>");
      out.print( tx.getDescription() );
      out.write("</td>\n");
      out.write("                        <td>");
      out.print( String.format("%.2f", tx.getAmount()) );
      out.write("</td>\n");
      out.write("                        <td>");
      out.print( String.format("%.2f", tx.getBalance()) );
      out.write("</td>\n");
      out.write("                    </tr>\n");
      out.write("                ");
 } 
      out.write("\n");
      out.write("                </tbody>\n");
      out.write("            </table>\n");
      out.write("        ");
 } 
      out.write("\n");
      out.write("    ");
 } 
      out.write("\n");
      out.write("</body>\n");
      out.write("</html>\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
